export const COUNTRIES = [
  { code: '+93', label: 'AF', name: 'Afghanistan', flag: '🇦🇫' },
  { code: '+355', label: 'AL', name: 'Albania', flag: '🇦🇱' },
  { code: '+213', label: 'DZ', name: 'Algeria', flag: '🇩🇿' },
  { code: '+1', label: 'AS', name: 'American Samoa', flag: '🇦🇸' },
  { code: '+376', label: 'AD', name: 'Andorra', flag: '🇦🇩' },
  { code: '+244', label: 'AO', name: 'Angola', flag: '🇦🇴' },
  { code: '+1', label: 'AI', name: 'Anguilla', flag: '🇦🇮' },
  { code: '+1', label: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬' },
  { code: '+54', label: 'AR', name: 'Argentina', flag: '🇦🇷' },
  { code: '+374', label: 'AM', name: 'Armenia', flag: '🇦🇲' },
  { code: '+297', label: 'AW', name: 'Aruba', flag: '🇦🇼' },
  { code: '+61', label: 'AU', name: 'Australia', flag: '🇦🇺' },
  { code: '+43', label: 'AT', name: 'Austria', flag: '🇦🇹' },
  { code: '+994', label: 'AZ', name: 'Azerbaijan', flag: '🇦🇿' },
  { code: '+1', label: 'BS', name: 'Bahamas', flag: '🇧🇸' },
  { code: '+973', label: 'BH', name: 'Bahrain', flag: '🇧🇭' },
  { code: '+880', label: 'BD', name: 'Bangladesh', flag: '🇧🇩' },
  { code: '+1', label: 'BB', name: 'Barbados', flag: '🇧🇧' },
  { code: '+375', label: 'BY', name: 'Belarus', flag: '🇧🇾' },
  { code: '+32', label: 'BE', name: 'Belgium', flag: '🇧🇪' },
  { code: '+501', label: 'BZ', name: 'Belize', flag: '🇧🇿' },
  { code: '+229', label: 'BJ', name: 'Benin', flag: '🇧🇯' },
  { code: '+1', label: 'BM', name: 'Bermuda', flag: '🇧🇲' },
  { code: '+975', label: 'BT', name: 'Bhutan', flag: '🇧🇹' },
  { code: '+591', label: 'BO', name: 'Bolivia', flag: '🇧🇴' },
  { code: '+387', label: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  { code: '+267', label: 'BW', name: 'Botswana', flag: '🇧🇼' },
  { code: '+55', label: 'BR', name: 'Brazil', flag: '🇧🇷' },
  { code: '+246', label: 'IO', name: 'British Indian Ocean Territory', flag: '🇮🇴' },
  { code: '+673', label: 'BN', name: 'Brunei Darussalam', flag: '🇧🇳' },
  { code: '+359', label: 'BG', name: 'Bulgaria', flag: '🇧🇬' },
  { code: '+226', label: 'BF', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: '+257', label: 'BI', name: 'Burundi', flag: '🇧🇮' },
  { code: '+855', label: 'KH', name: 'Cambodia', flag: '🇰🇭' },
  { code: '+237', label: 'CM', name: 'Cameroon', flag: '🇨🇲' },
  { code: '+1', label: 'CA', name: 'Canada', flag: '🇨🇦' },
  { code: '+238', label: 'CV', name: 'Cape Verde', flag: '🇨🇻' },
  { code: '+1', label: 'KY', name: 'Cayman Islands', flag: '🇰🇾' },
  { code: '+236', label: 'CF', name: 'Central African Republic', flag: '🇨🇫' },
  { code: '+235', label: 'TD', name: 'Chad', flag: '🇹🇩' },
  { code: '+56', label: 'CL', name: 'Chile', flag: '🇨🇱' },
  { code: '+86', label: 'CN', name: 'China', flag: '🇨🇳' },
  { code: '+57', label: 'CO', name: 'Colombia', flag: '🇨🇴' },
  { code: '+269', label: 'KM', name: 'Comoros', flag: '🇰🇲' },
  { code: '+243', label: 'CG', name: 'Congo', flag: '🇨🇬' },
  { code: '+243', label: 'CD', name: 'Congo, Democratic Republic of the', flag: '🇨🇩' },
  { code: '+682', label: 'CK', name: 'Cook Islands', flag: '🇨🇰' },
  { code: '+506', label: 'CR', name: 'Costa Rica', flag: '🇨🇷' },
  { code: '+225', label: 'CI', name: 'Cote d\'Ivoire', flag: '🇨🇮' },
  { code: '+385', label: 'HR', name: 'Croatia', flag: '🇭🇷' },
  { code: '+53', label: 'CU', name: 'Cuba', flag: '🇨🇺' },
  { code: '+357', label: 'CY', name: 'Cyprus', flag: '🇨🇾' },
  { code: '+420', label: 'CZ', name: 'Czech Republic', flag: '🇨🇿' },
  { code: '+45', label: 'DK', name: 'Denmark', flag: '🇩🇰' },
  { code: '+253', label: 'DJ', name: 'Djibouti', flag: '🇩🇯' },
  { code: '+1', label: 'DM', name: 'Dominica', flag: '🇩🇲' },
  { code: '+1', label: 'DO', name: 'Dominican Republic', flag: '🇩🇴' },
  { code: '+593', label: 'EC', name: 'Ecuador', flag: '🇪🇨' },
  { code: '+20', label: 'EG', name: 'Egypt', flag: '🇪🇬' },
  { code: '+503', label: 'SV', name: 'El Salvador', flag: '🇸🇻' },
  { code: '+240', label: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶' },
  { code: '+291', label: 'ER', name: 'Eritrea', flag: '🇪🇷' },
  { code: '+372', label: 'EE', name: 'Estonia', flag: '🇪🇪' },
  { code: '+251', label: 'ET', name: 'Ethiopia', flag: '🇪🇹' },
  { code: '+500', label: 'FK', name: 'Falkland Islands (Malvinas)', flag: '🇫🇰' },
  { code: '+298', label: 'FO', name: 'Faroe Islands', flag: '🇫🇴' },
  { code: '+679', label: 'FJ', name: 'Fiji', flag: '🇫🇯' },
  { code: '+358', label: 'FI', name: 'Finland', flag: '🇫🇮' },
  { code: '+33', label: 'FR', name: 'France', flag: '🇫🇷' },
  { code: '+594', label: 'GF', name: 'French Guiana', flag: '🇬🇫' },
  { code: '+689', label: 'PF', name: 'French Polynesia', flag: '🇵🇫' },
  { code: '+241', label: 'GA', name: 'Gabon', flag: '🇬🇦' },
  { code: '+220', label: 'GM', name: 'Gambia', flag: '🇬🇲' },
  { code: '+995', label: 'GE', name: 'Georgia', flag: '🇬🇪' },
  { code: '+49', label: 'DE', name: 'Germany', flag: '🇩🇪' },
  { code: '+233', label: 'GH', name: 'Ghana', flag: '🇬🇭' },
  { code: '+350', label: 'GI', name: 'Gibraltar', flag: '🇬🇮' },
  { code: '+30', label: 'GR', name: 'Greece', flag: '🇬🇷' },
  { code: '+299', label: 'GL', name: 'Greenland', flag: '🇬🇱' },
  { code: '+1', label: 'GD', name: 'Grenada', flag: '🇬🇩' },
  { code: '+590', label: 'GP', name: 'Guadeloupe', flag: '🇬🇵' },
  { code: '+1', label: 'GU', name: 'Guam', flag: '🇬🇺' },
  { code: '+502', label: 'GT', name: 'Guatemala', flag: '🇬🇹' },
  { code: '+224', label: 'GN', name: 'Guinea', flag: '🇬🇳' },
  { code: '+245', label: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼' },
  { code: '+592', label: 'GY', name: 'Guyana', flag: '🇬🇾' },
  { code: '+509', label: 'HT', name: 'Haiti', flag: '🇭🇹' },
  { code: '+39', label: 'VA', name: 'Holy See (Vatican City State)', flag: '🇻🇦' },
  { code: '+504', label: 'HN', name: 'Honduras', flag: '🇭🇳' },
  { code: '+852', label: 'HK', name: 'Hong Kong', flag: '🇭🇰' },
  { code: '+36', label: 'HU', name: 'Hungary', flag: '🇭🇺' },
  { code: '+354', label: 'IS', name: 'Iceland', flag: '🇮🇸' },
  { code: '+91', label: 'IN', name: 'India', flag: '🇮🇳' },
  { code: '+62', label: 'ID', name: 'Indonesia', flag: '🇮🇩' },
  { code: '+98', label: 'IR', name: 'Iran, Islamic Republic of', flag: '🇮🇷' },
  { code: '+964', label: 'IQ', name: 'Iraq', flag: '🇮🇶' },
  { code: '+353', label: 'IE', name: 'Ireland', flag: '🇮🇪' },
  { code: '+972', label: 'IL', name: 'Israel', flag: '🇮🇱' },
  { code: '+39', label: 'IT', name: 'Italy', flag: '🇮🇹' },
  { code: '+1', label: 'JM', name: 'Jamaica', flag: '🇯🇲' },
  { code: '+81', label: 'JP', name: 'Japan', flag: '🇯🇵' },
  { code: '+962', label: 'JO', name: 'Jordan', flag: '🇯🇴' },
  { code: '+7', label: 'KZ', name: 'Kazakhstan', flag: '🇰🇿' },
  { code: '+254', label: 'KE', name: 'Kenya', flag: '🇰🇪' },
  { code: '+686', label: 'KI', name: 'Kiribati', flag: '🇰🇮' },
  { code: '+850', label: 'KP', name: 'Korea, Democratic People\'s Republic of', flag: '🇰🇵' },
  { code: '+82', label: 'KR', name: 'Korea, Republic of', flag: '🇰🇷' },
  { code: '+965', label: 'KW', name: 'Kuwait', flag: '🇰🇼' },
  { code: '+996', label: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬' },
  { code: '+856', label: 'LA', name: 'Lao People\'s Democratic Republic', flag: '🇱🇦' },
  { code: '+371', label: 'LV', name: 'Latvia', flag: '🇱🇻' },
  { code: '+961', label: 'LB', name: 'Lebanon', flag: '🇱🇧' },
  { code: '+266', label: 'LS', name: 'Lesotho', flag: '🇱🇸' },
  { code: '+231', label: 'LR', name: 'Liberia', flag: '🇱🇷' },
  { code: '+218', label: 'LY', name: 'Libyan Arab Jamahiriya', flag: '🇱🇾' },
  { code: '+423', label: 'LI', name: 'Liechtenstein', flag: '🇱🇮' },
  { code: '+370', label: 'LT', name: 'Lithuania', flag: '🇱🇹' },
  { code: '+352', label: 'LU', name: 'Luxembourg', flag: '🇱🇺' },
  { code: '+853', label: 'MO', name: 'Macao', flag: '🇲🇴' },
  { code: '+389', label: 'MK', name: 'Macedonia, The Former Yugoslav Republic of', flag: '🇲🇰' },
  { code: '+261', label: 'MG', name: 'Madagascar', flag: '🇲🇬' },
  { code: '+265', label: 'MW', name: 'Malawi', flag: '🇲🇼' },
  { code: '+60', label: 'MY', name: 'Malaysia', flag: '🇲🇾' },
  { code: '+960', label: 'MV', name: 'Maldives', flag: '🇲🇻' },
  { code: '+223', label: 'ML', name: 'Mali', flag: '🇲🇱' },
  { code: '+356', label: 'MT', name: 'Malta', flag: '🇲🇹' },
  { code: '+692', label: 'MH', name: 'Marshall Islands', flag: '🇲🇭' },
  { code: '+596', label: 'MQ', name: 'Martinique', flag: '🇲🇶' },
  { code: '+222', label: 'MR', name: 'Mauritania', flag: '🇲🇷' },
  { code: '+230', label: 'MU', name: 'Mauritius', flag: '🇲🇺' },
  { code: '+262', label: 'YT', name: 'Mayotte', flag: '🇾🇹' },
  { code: '+52', label: 'MX', name: 'Mexico', flag: '🇲🇽' },
  { code: '+691', label: 'FM', name: 'Micronesia, Federated States of', flag: '🇫🇲' },
  { code: '+373', label: 'MD', name: 'Moldova, Republic of', flag: '🇲🇩' },
  { code: '+377', label: 'MC', name: 'Monaco', flag: '🇲🇨' },
  { code: '+976', label: 'MN', name: 'Mongolia', flag: '🇲🇳' },
  { code: '+1', label: 'MS', name: 'Montserrat', flag: '🇲🇸' },
  { code: '+212', label: 'MA', name: 'Morocco', flag: '🇲🇦' },
  { code: '+258', label: 'MZ', name: 'Mozambique', flag: '🇲🇿' },
  { code: '+95', label: 'MM', name: 'Myanmar', flag: '🇲🇲' },
  { code: '+264', label: 'NA', name: 'Namibia', flag: '🇳🇦' },
  { code: '+674', label: 'NR', name: 'Nauru', flag: '🇳🇷' },
  { code: '+977', label: 'NP', name: 'Nepal', flag: '🇳🇵' },
  { code: '+31', label: 'NL', name: 'Netherlands', flag: '🇳🇱' },
  { code: '+599', label: 'AN', name: 'Netherlands Antilles', flag: '🇳🇱' },
  { code: '+687', label: 'NC', name: 'New Caledonia', flag: '🇳🇨' },
  { code: '+64', label: 'NZ', name: 'New Zealand', flag: '🇳🇿' },
  { code: '+505', label: 'NI', name: 'Nicaragua', flag: '🇳🇮' },
  { code: '+227', label: 'NE', name: 'Niger', flag: '🇳🇪' },
  { code: '+234', label: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  { code: '+683', label: 'NU', name: 'Niue', flag: '🇳🇺' },
  { code: '+672', label: 'NF', name: 'Norfolk Island', flag: '🇳🇫' },
  { code: '+1', label: 'MP', name: 'Northern Mariana Islands', flag: '🇲🇵' },
  { code: '+47', label: 'NO', name: 'Norway', flag: '🇳🇴' },
  { code: '+968', label: 'OM', name: 'Oman', flag: '🇴🇲' },
  { code: '+92', label: 'PK', name: 'Pakistan', flag: '🇵🇰' },
  { code: '+680', label: 'PW', name: 'Palau', flag: '🇵🇼' },
  { code: '+970', label: 'PS', name: 'Palestinian Territory, Occupied', flag: '🇵🇸' },
  { code: '+507', label: 'PA', name: 'Panama', flag: '🇵🇦' },
  { code: '+675', label: 'PG', name: 'Papua New Guinea', flag: '🇵🇬' },
  { code: '+595', label: 'PY', name: 'Paraguay', flag: '🇵🇾' },
  { code: '+51', label: 'PE', name: 'Peru', flag: '🇵🇪' },
  { code: '+63', label: 'PH', name: 'Philippines', flag: '🇵🇭' },
  { code: '+64', label: 'PN', name: 'Pitcairn', flag: '🇵🇳' },
  { code: '+48', label: 'PL', name: 'Poland', flag: '🇵🇱' },
  { code: '+351', label: 'PT', name: 'Portugal', flag: '🇵🇹' },
  { code: '+1', label: 'PR', name: 'Puerto Rico', flag: '🇵🇷' },
  { code: '+974', label: 'QA', name: 'Qatar', flag: '🇶🇦' },
  { code: '+262', label: 'RE', name: 'Reunion', flag: '🇷🇪' },
  { code: '+40', label: 'RO', name: 'Romania', flag: '🇷🇴' },
  { code: '+7', label: 'RU', name: 'Russian Federation', flag: '🇷🇺' },
  { code: '+250', label: 'RW', name: 'Rwanda', flag: '🇷🇼' },
  { code: '+290', label: 'SH', name: 'Saint Helena', flag: '🇸🇭' },
  { code: '+1', label: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳' },
  { code: '+1', label: 'LC', name: 'Saint Lucia', flag: '🇱🇨' },
  { code: '+508', label: 'PM', name: 'Saint Pierre and Miquelon', flag: '🇵🇲' },
  { code: '+1', label: 'VC', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨' },
  { code: '+685', label: 'WS', name: 'Samoa', flag: '🇼🇸' },
  { code: '+378', label: 'SM', name: 'San Marino', flag: '🇸🇲' },
  { code: '+239', label: 'ST', name: 'Sao Tome and Principe', flag: '🇸🇹' },
  { code: '+966', label: 'SA', name: 'Saudi Arabia', flag: '🇸🇦' },
  { code: '+221', label: 'SN', name: 'Senegal', flag: '🇸🇳' },
  { code: '+381', label: 'CS', name: 'Serbia and Montenegro', flag: '🇷🇸' },
  { code: '+248', label: 'SC', name: 'Seychelles', flag: '🇸🇨' },
  { code: '+232', label: 'SL', name: 'Sierra Leone', flag: '🇸🇱' },
  { code: '+65', label: 'SG', name: 'Singapore', flag: '🇸🇬' },
  { code: '+421', label: 'SK', name: 'Slovakia', flag: '🇸🇰' },
  { code: '+386', label: 'SI', name: 'Slovenia', flag: '🇸🇮' },
  { code: '+677', label: 'SB', name: 'Solomon Islands', flag: '🇸🇧' },
  { code: '+252', label: 'SO', name: 'Somalia', flag: '🇸🇴' },
  { code: '+27', label: 'ZA', name: 'South Africa', flag: '🇿🇦' },
  { code: '+34', label: 'ES', name: 'Spain', flag: '🇪🇸' },
  { code: '+94', label: 'LK', name: 'Sri Lanka', flag: '🇱🇰' },
  { code: '+249', label: 'SD', name: 'Sudan', flag: '🇸🇩' },
  { code: '+597', label: 'SR', name: 'Suriname', flag: '🇸🇷' },
  { code: '+47', label: 'SJ', name: 'Svalbard and Jan Mayen', flag: '🇸🇯' },
  { code: '+268', label: 'SZ', name: 'Swaziland', flag: '🇸🇿' },
  { code: '+46', label: 'SE', name: 'Sweden', flag: '🇸🇪' },
  { code: '+41', label: 'CH', name: 'Switzerland', flag: '🇨🇭' },
  { code: '+963', label: 'SY', name: 'Syrian Arab Republic', flag: '🇸🇾' },
  { code: '+886', label: 'TW', name: 'Taiwan, Province of China', flag: '🇹🇼' },
  { code: '+992', label: 'TJ', name: 'Tajikistan', flag: '🇹🇯' },
  { code: '+255', label: 'TZ', name: 'Tanzania, United Republic of', flag: '🇹🇿' },
  { code: '+66', label: 'TH', name: 'Thailand', flag: '🇹🇭' },
  { code: '+670', label: 'TL', name: 'Timor-Leste', flag: '🇹🇱' },
  { code: '+228', label: 'TG', name: 'Togo', flag: '🇹🇬' },
  { code: '+690', label: 'TK', name: 'Tokelau', flag: '🇹🇰' },
  { code: '+676', label: 'TO', name: 'Tonga', flag: '🇹🇴' },
  { code: '+1', label: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹' },
  { code: '+216', label: 'TN', name: 'Tunisia', flag: '🇹🇳' },
  { code: '+90', label: 'TR', name: 'Turkey', flag: '🇹🇷' },
  { code: '+993', label: 'TM', name: 'Turkmenistan', flag: '🇹🇲' },
  { code: '+1', label: 'TC', name: 'Turks and Caicos Islands', flag: '🇹🇨' },
  { code: '+688', label: 'TV', name: 'Tuvalu', flag: '🇹🇻' },
  { code: '+256', label: 'UG', name: 'Uganda', flag: '🇺🇬' },
  { code: '+380', label: 'UA', name: 'Ukraine', flag: '🇺🇦' },
  { code: '+971', label: 'AE', name: 'United Arab Emirates', flag: '🇦🇪' },
  { code: '+44', label: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
  { code: '+1', label: 'US', name: 'United States', flag: '🇺🇸' },
  { code: '+598', label: 'UY', name: 'Uruguay', flag: '🇺🇾' },
  { code: '+998', label: 'UZ', name: 'Uzbekistan', flag: '🇺🇿' },
  { code: '+678', label: 'VU', name: 'Vanuatu', flag: '🇻🇺' },
  { code: '+58', label: 'VE', name: 'Venezuela', flag: '🇻🇪' },
  { code: '+84', label: 'VN', name: 'Viet Nam', flag: '🇻🇳' },
  { code: '+1', label: 'VG', name: 'Virgin Islands, British', flag: '🇻🇬' },
  { code: '+1', label: 'VI', name: 'Virgin Islands, U.s.', flag: '🇻🇮' },
  { code: '+681', label: 'WF', name: 'Wallis and Futuna', flag: '🇼🇫' },
  { code: '+967', label: 'YE', name: 'Yemen', flag: '🇾🇪' },
  { code: '+260', label: 'ZM', name: 'Zambia', flag: '🇿🇲' },
  { code: '+263', label: 'ZW', name: 'Zimbabwe', flag: '🇿🇼' }
];
